name: build

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  build:
    strategy:
      matrix:
        include:
          # - target: x86_64-apple-darwin
          #   os: macos-13
          # - target: aarch64-apple-darwin
          #   os: macos-latest
          # - target: x86_64-pc-windows-msvc
          #   os: windows-latest
          # - target: x86_64-pc-windows-gnu
          #   os: windows-latest
          # - target: arm64ec-pc-windows-msvc
          #   os: windows-latest
          # - target: aarch64-unknown-linux-musl
          #   os: ubuntu-latest
          # - target: aarch64-unknown-linux-gnu
          #   os: ubuntu-latest
          # - target: x86_64-unknown-linux-musl
          #   os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-2404
    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - name: build-${{ matrix.target }}
        if: matrix.os != 'windows-latest'
        shell: "bash"
        run: |
          sudo apt update -y
          sudo apt-get install autoconf autoconf-archive gettext gettext-base autopoint build-essential libc6-dev txt2man -y
          git clone https://github.com/axel-download-accelerator/axel

          cd axel

          autoreconf -i
          ./configure
          make

          mkdir ../dist

          cp ./axel ../dist/axel

          cd ..
          tar -czf ./axel-${{ matrix.target }}.tar.gz -C ./dist .
          ls -l ./axel-${{ matrix.target }}.tar.gz

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: axel-${{ matrix.target }}
          path: ./axel-${{ matrix.target }}.tar.gz
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: axel
          pattern: axel*
          merge-multiple: true

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "axel/*.tar.gz"
